const { Rule } = require('../src')

test('even', () => {
  const rule = new Rule('#{ number: num }', 'even', 'num | mod 2 | equal 0')
  expect(rule.transpile('1')).toEqual(null)
  expect(rule.transpile('2')).toEqual('even')
  expect(rule.transpile('3')).toEqual(null)
  expect(rule.transpile('4')).toEqual('even')
  expect(rule.transpile('5')).toEqual(null)
  expect(rule.transpile('6')).toEqual('even')
  expect(rule.transpile('7')).toEqual(null)
  expect(rule.transpile('8')).toEqual('even')
  expect(rule.transpile('9')).toEqual(null)
  expect(rule.transpile('10')).toEqual('even')
  expect(rule.transpile('11')).toEqual(null)
  expect(rule.transpile('12')).toEqual('even')
})

test('odd', () => {
  const rule = new Rule('#{ number: num }', 'odd', 'num | mod 2 | equal 1')
  expect(rule.transpile('1')).toEqual('odd')
  expect(rule.transpile('2')).toEqual(null)
  expect(rule.transpile('3')).toEqual('odd')
  expect(rule.transpile('4')).toEqual(null)
  expect(rule.transpile('5')).toEqual('odd')
  expect(rule.transpile('6')).toEqual(null)
  expect(rule.transpile('7')).toEqual('odd')
  expect(rule.transpile('8')).toEqual(null)
  expect(rule.transpile('9')).toEqual('odd')
  expect(rule.transpile('10')).toEqual(null)
  expect(rule.transpile('11')).toEqual('odd')
  expect(rule.transpile('12')).toEqual(null)
})
